/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tpl.group2.labcasestudy;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Scanner;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import materials.TextLineNumber;
/**
 *
 * @author USER
 */
public class GUI extends javax.swing.JFrame {

    //declared variables
    String txtResultDefined = "Result: ";
    List<String> inputList = new ArrayList();

    InputManager inputManager;
    //Colors
    //rgba(10,25,47,255)
    Color primaryColor = new Color(10,25,47,255);
    //rgba(23,42,70,255)
    Color secondaryColor = new Color(23,42,70,255);
    Color textPrimaryColor = new Color(255,255,255,255);
    Color textSecondaryColor = new Color(200,200,200,255);
    Color buttonColor = new Color(23,42,70,255);
    
    //Fonts
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        MainVirtual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        scrPaneInput = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();
        pnlInputTitle = new materials.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        scrPaneResult = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        pnlResultTitle = new javax.swing.JPanel();
        txtResultTitle = new javax.swing.JTextField();
        panelLeft = new javax.swing.JPanel();
        pnlButtonAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlButtonAdd1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(getPrimaryColor());
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(32, 32));

        panelMain.setBackground(getPrimaryColor());

        scrPaneInput.setBackground(getPrimaryColor());
        scrPaneInput.setBorder(null);

        txtInput.setBackground(getSecondaryColor());
        txtInput.setColumns(20);
        txtInput.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtInput.setForeground(getTextPrimaryColor());
        txtInput.setLineWrap(true);
        txtInput.setRows(5);
        txtInput.setText("int i =10;\nString watashi = \"uwu\";\nchar c = 'c';");
        txtInput.setBorder(null);
        txtInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtInput.setMargin(new java.awt.Insets(0, 0, 0, 0));
        scrPaneInput.setViewportView(txtInput);

        pnlInputTitle.setBackground(getSecondaryColor());
        pnlInputTitle.setRoundTopLeft(25);
        pnlInputTitle.setRoundTopRight(25);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setForeground(getTextPrimaryColor());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Text.txt");

        javax.swing.GroupLayout pnlInputTitleLayout = new javax.swing.GroupLayout(pnlInputTitle);
        pnlInputTitle.setLayout(pnlInputTitleLayout);
        pnlInputTitleLayout.setHorizontalGroup(
            pnlInputTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        pnlInputTitleLayout.setVerticalGroup(
            pnlInputTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputTitleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        scrPaneResult.setBorder(null);

        txtResult.setEditable(false);
        txtResult.setBackground(getSecondaryColor());
        txtResult.setColumns(20);
        txtResult.setForeground(getTextPrimaryColor());
        txtResult.setRows(5);
        txtResult.setText("<data_type><identifier>");
        txtResult.setBorder(null);
        txtResult.setMargin(new java.awt.Insets(0, 6, 0, 6));
        scrPaneResult.setViewportView(txtResult);

        pnlResultTitle.setBackground(getSecondaryColor());

        txtResultTitle.setBackground(getSecondaryColor());
        txtResultTitle.setForeground(getTextPrimaryColor());
        txtResultTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultTitle.setText("Result");
        txtResultTitle.setBorder(null);
        txtResultTitle.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtResultTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResultTitleLayout = new javax.swing.GroupLayout(pnlResultTitle);
        pnlResultTitle.setLayout(pnlResultTitleLayout);
        pnlResultTitleLayout.setHorizontalGroup(
            pnlResultTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResultTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultTitleLayout.setVerticalGroup(
            pnlResultTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtResultTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInputTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrPaneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlResultTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrPaneResult, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(pnlInputTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPaneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlResultTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrPaneResult, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );

        panelLeft.setBackground(getSecondaryColor());

        pnlButtonAdd.setBackground(getSecondaryColor());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(getTextSecondaryColor());
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Open Document");

        pnlButtonAdd1.setBackground(getSecondaryColor());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(getTextSecondaryColor());
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Clean Document");

        javax.swing.GroupLayout pnlButtonAdd1Layout = new javax.swing.GroupLayout(pnlButtonAdd1);
        pnlButtonAdd1.setLayout(pnlButtonAdd1Layout);
        pnlButtonAdd1Layout.setHorizontalGroup(
            pnlButtonAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonAdd1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        pnlButtonAdd1Layout.setVerticalGroup(
            pnlButtonAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonAdd1Layout.createSequentialGroup()
                .addGroup(pnlButtonAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlButtonAddLayout = new javax.swing.GroupLayout(pnlButtonAdd);
        pnlButtonAdd.setLayout(pnlButtonAddLayout);
        pnlButtonAddLayout.setHorizontalGroup(
            pnlButtonAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonAddLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addComponent(pnlButtonAdd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlButtonAddLayout.setVerticalGroup(
            pnlButtonAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonAddLayout.createSequentialGroup()
                .addGroup(pnlButtonAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(pnlButtonAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(pnlButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    void MainVirtual(){
        TextLineNumber tln = new TextLineNumber(txtInput);
        tln.setBackground(secondaryColor);
        tln.setForeground(textPrimaryColor);
        tln.setBorder(null);
        
        tln.setDigitAlignment(CENTER_ALIGNMENT);
        tln.setCurrentLineForeground(textSecondaryColor);
        scrPaneInput.setRowHeaderView(tln);
        //scrPaneInput.getRowHeader().setBackground(Color.red);
        getContentPane().setBackground( primaryColor);
        
        //Buttons
        Border emptyBorder = BorderFactory.createEmptyBorder(4, 4, 4, 4);
        //btnSemantic.setBorder(emptyBorder);
        //btnSemantic.setContentAreaFilled(false);
        
    }
    private void txtResultTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    void BtnOpen(){
        CleanButton();
        String path = System.getProperty("user.home") + "/Desktop/Input1.txt";
        JFileChooser chooser = new JFileChooser(path);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        try {
            Scanner scan = new Scanner(f);
            String txt = "";
            while (scan.hasNextLine()) {
                String next = scan.nextLine();
                inputList.add(next);
                txt+=next +"\n";
            }
            txtInput.setText(txt);
            inputManager = new InputManager(inputList);
            //btnLexical.setEnabled(true);
            //btnSyntax.setVisible(false);
            //btnSemantic.setVisible(false);
        } catch (FileNotFoundException ex) {
            SetResultTextView("File is not found");
        }
    }
    
    void BtnLexical(){
        inputManager.LexicalAnalysis();
        String output = "";
        for(InputObject inputObj: inputManager.getInputObjectList()){
            for(String token: inputObj.getTokenList()){
                output +=token+" ";
            }
            output+="\n";
        }
        SetResultTextView(output);
        //btnSyntax.setEnabled(true);
        //btnSyntax.setVisible(true);
        //btnLexical.setVisible(false);
    }
    void BtnSyntax(){
        List<Boolean> syntaxList = inputManager.SyntaxAnalysis();
        boolean isThereFalse = false;
        String txt ="";
        for(boolean tf: syntaxList){
            if (!tf) {
             txt +="Syntax is not valid!!\n";
             isThereFalse = true;
             continue;
            }
            txt+="Syntax is valid!!\n";
        }
        SetResultTextView(txt);
        //if(!isThereFalse)btnSemantic.setEnabled(true); 
        //btnSyntax.setVisible(false);
        //btnSemantic.setVisible(true);
    }
    void BtnSemantic(){
        List<Boolean> semanticList = inputManager.SemanticAnalysis();
        boolean isThereFalse = false;
        String txt="";
        for(boolean tf: semanticList){
             if (!tf) {
                txt +="Semantic is not valid!!\n";
                continue;
                }
           txt+="Semantic is valid!!\n";  
        }
        SetResultTextView(txt);
    }
        
    //Methods
    void SetResultTextView(String text) {
        txtResult.setText(txtResultDefined+ "\n"+ text);
    }

    Color getPrimaryColor(){
        return primaryColor;
    }
    Color getSecondaryColor(){
        return secondaryColor;
    }
    Color getTextPrimaryColor(){
        return textPrimaryColor;
    }
    Color getTextSecondaryColor(){
        return textSecondaryColor;
    }
    void CleanButton() {
        txtInput.setText("");
        txtResult.setText("");
        inputManager = null;
        inputList = new ArrayList();
        //btnLexical.setEnabled(false);
        //btnSyntax.setEnabled(false);
        //btnSemantic.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel pnlButtonAdd;
    private javax.swing.JPanel pnlButtonAdd1;
    private materials.PanelRound pnlInputTitle;
    private javax.swing.JPanel pnlResultTitle;
    private javax.swing.JScrollPane scrPaneInput;
    private javax.swing.JScrollPane scrPaneResult;
    private javax.swing.JTextArea txtInput;
    private javax.swing.JTextArea txtResult;
    private javax.swing.JTextField txtResultTitle;
    // End of variables declaration//GEN-END:variables
}
